language: python
sudo: false
python:
- '2.7'
- '3.4'
before_install:
- cd ./python
install:
- echo foo
script:
- echo foo
deploy:
  provider: pypi
  user: wielandbrendel
  password:
    secure: eTi3JIOoahb8qxLMZwwxECuWsHIZ26NWp1ICWc4CnCjOHxS+Kli3W9I1FtTkd6r7tOl5LuPf8iObiMGu/sW3oLP2fELbRIgNsUreFfiNwax+KgnYyfVIKCF0hMT+Qd13mXyrPvHyxJ795UCru+gUYqebNYaB4R5KcJLL1+GaEzqGRIBMrTfZ5vomY2wa2Z/fRvLPWKsAHrs3ErcGoN1XNOJtmCYmwIvejbXOImWmJKgojaqtXQ6ZmvM7ZTAK/G+KKWrnJO1EDVATrheLfbEZUNlCxRt2TZebnIDnqaSHZnKgqpHm5vCkdviLi1cBe68rkugorpvqpRbxOdXL/9CCK/tWH6kTa03etDTUh4FU0JnTVD1KycWXpDsqpbFNFn+kZNLIaHFKtzTPvLwLu3b8+y+lD3XJz9EIe7hUFTkAoi1GzXk7gAGv/3z6vmBYodhECDFQmNRzl2rZlWeu1EUFz/PCDwqhPyg5zNFNmC+/c/BxSX4kPqQKRtHmf1dvoZ84S2tP5dOkQBcY1rolrSeEQ//MxvAWI63qpseTF3qPoQKoX5+kQEwxoNT28wAFSyN+TucbvPDkukWjWMTiMoULXHcCSjxTgZlOaepB7OwZ+1O8XiS2A6NJgEtVMLBId6Zaq4zdqEu+LwQett40hBBZGyR4m8rUjFjyyIv7EYJPT7A=
  on:
    repo: machenslab/dPCA
